### ISSUE TITLE
does it even work?

### ISSUE THREAD

**Issue by adelsaramii** [realityexpander/ContactsComposeMultiplatform#1]
you used google maps apis for ios too
does it work? can you show us the result

**Comment by realityexpander** [comment]
You can display items on the map, but you cant respond to taps yet. There's a problem on the Google Maps side, they need to update their library to make it work on iOS for Google Maps if you are looking for tap responses.

I assume they know about the issues and are working on a release soon.

**Comment by adelsaramii** [comment]
where can i find reference for this library from Google?

**Comment by realityexpander** [comment]
You mean the Google Maps SDK?

Do you need to hire me to help you do this?

Best,
Chris
